INSERT INTO clubs (club_name, description, category, contact_email, status)
VALUES
    ('Apple Centre of Excellence', 'Advanced iOS application engineering, Swift/SwiftUI development, and Apple ecosystem research.', 'center_of_excellence', 'applecenter@ritchennai.edu.in', 'active'),
    ('VR & AR Centre of Excellence', 'Virtual Reality, Augmented Reality, 3D spatial computing, and HoloLens 2 immersive simulation labs.', 'center_of_excellence', 'vrcenter@ritchennai.edu.in', 'active'),
    ('Cyber Security & Digital Forensics Centre', 'Network defense, ethical hacking, cryptography, vulnerability assessment, and digital forensics research.', 'center_of_excellence', 'cybersecurity@ritchennai.edu.in', 'active'),
    ('AI & Robotics Centre of Excellence', 'Artificial intelligence, computer vision, autonomous robotics, and machine learning solutions.', 'center_of_excellence', 'airobotics@ritchennai.edu.in', 'active'),
    ('IoT & Smart Systems Centre', 'Internet of Things, embedded hardware design, smart sensor networks, and edge computing.', 'center_of_excellence', 'iotcenter@ritchennai.edu.in', 'active'),
    ('Electric Vehicle & Green Tech Centre', 'EV powertrain engineering, battery management systems, and sustainable green technology research.', 'center_of_excellence', 'evcenter@ritchennai.edu.in', 'active'),
    ('Coding Club', 'Competitive programming, algorithm design, LeetCode challenges, and open-source software development.', 'technical', 'codingclub@ritchennai.edu.in', 'active'),
    ('Google Developer Student Club', 'Peer learning, Android/Flutter development, Cloud, and building solutions with Google developer tools.', 'technical', 'gdsc@ritchennai.edu.in', 'active'),
    ('Infinitus Club', 'Cutting-edge innovation, Scopus research publication guidance, SIH hackathons, and patent filings.', 'technical', 'infinitus@ritchennai.edu.in', 'active'),
    ('Vaarithi Muthamizh Mandram', 'Tamil literary heritage, debate (Pattimandram), elocution, and regional cultural celebrations.', 'cultural', 'tamilsociety@ritchennai.edu.in', 'active'),
    ('Artist League', 'Fine arts, graphic design, posters, visual branding, and digital illustration showcases.', 'cultural', 'artistleague@ritchennai.edu.in', 'active'),
    ('Podcast (POD) Club', 'Audio podcasting, video production, interviewing campus guests, and audio engineering.', 'cultural', 'podcast@ritchennai.edu.in', 'active'),
    ('Nippon Club', 'Japanese language proficiency (JLPT N5/N4), cultural immersion, and career preparation for Japanese MNCs.', 'language', 'nippon@ritchennai.edu.in', 'active'),
    ('Telugu Club', 'Telugu literary meets, cultural celebrations, public speaking, and regional heritage workshops.', 'cultural', 'telugu@ritchennai.edu.in', 'active'),
    ('Mediastic Hub', 'Campus journalism, social media coverage, video editing, and institutional public relations.', 'cultural', 'mediastichub@ritchennai.edu.in', 'active'),
    ('Unnat Bharat Abhiyan (UBA)', 'Rural development, adoption of local villages, and applying engineering solutions to community challenges.', 'service', 'uba@ritchennai.edu.in', 'active'),
    ('National Service Scheme (NSS)', 'Community social service, 7-day annual rural camps, blood donation drives, and civic responsibility.', 'service', 'nss@ritchennai.edu.in', 'active'),
    ('Youth Red Cross (YRC)', 'First aid training, disaster relief assistance, health awareness rallies, and voluntary blood donor registry.', 'service', 'yrc@ritchennai.edu.in', 'active'),
    ('STEAM Club', 'Interdisciplinary innovation in science, technology, engineering, arts, and maths.', 'technical', 'steam@ritchennai.edu.in', 'active'),
    ('IoT Club', 'Hands-on projects in sensors, embedded systems, and smart campus automation.', 'technical', 'iotclub@ritchennai.edu.in', 'active'),
    ('CAM Club', 'Computer-aided modelling and manufacturing discussions and workshops.', 'technical', 'camclub@ritchennai.edu.in', 'active'),
    ('Techsparks Club', 'Student-led technology events, hackathons, and peer mentoring.', 'technical', 'techsparks@ritchennai.edu.in', 'active'),
    ('Language Club', 'Communication, debate, and multilingual proficiency initiatives.', 'language', 'languageclub@ritchennai.edu.in', 'active'),
    ('Maths Club', 'Problem solving circles, olympiad prep, and applied mathematics sessions.', 'technical', 'mathsclub@ritchennai.edu.in', 'active'),
    ('Rotaract Club', 'Community service and social impact initiatives with student leadership.', 'service', 'rotaract@ritchennai.edu.in', 'active'),
    ('YUVA Club', 'Youth leadership and civic engagement programmes for holistic growth.', 'service', 'yuva@ritchennai.edu.in', 'active'),
    ('Photography Club', 'Creative photography, media storytelling, and event documentation.', 'cultural', 'photography@ritchennai.edu.in', 'active'),
    ('Women Empowerment Club', 'Awareness, mentoring, and empowerment activities for inclusivity.', 'service', 'wec@ritchennai.edu.in', 'active')
ON DUPLICATE KEY UPDATE
    description = VALUES(description),
    category = VALUES(category),
    contact_email = VALUES(contact_email),
    status = VALUES(status);
