export const RIT_CAMPUS = {
  CENTER: { lat: 13.0382427, lng: 80.0453935 },
  ZOOM: 18,
  TILT: 60,
  HEADING: 320,
  AREA_SQM: 44029,
  BUILT_SQM: 16297,
  BUILDINGS: [
    {
      id: "tech_centre",
      name: "Tech Centre Block",
      shortName: "Tech Centre",
      type: "ACADEMIC",
      footprint: [[-55, -10], [-55, 35], [-10, 35], [-10, 55], [25, 55], [25, -10]],
      height: 22,
      floors: 5,
      color: "#C5A882",
      roofColor: "#8B7355",
      windowColor: "#4A90D9",
      departments: ["CSE", "AIDS", "CCE"],
      iotSensors: ["energy", "occupancy", "temperature", "air_quality"],
      landmark: true,
    },
    {
      id: "cv_raman_block",
      name: "Sir C.V. Raman Block",
      shortName: "C.V. Raman",
      type: "ACADEMIC",
      footprint: [[30, -10], [30, 50], [80, 50], [80, -10]],
      height: 18,
      floors: 4,
      color: "#B8C4C8",
      roofColor: "#7A8B8F",
      windowColor: "#5BA3E0",
      departments: ["ECE", "MECH", "CIVIL"],
      iotSensors: ["energy", "occupancy", "temperature"],
      landmark: true,
    },
    {
      id: "green_building",
      name: "Green Building",
      shortName: "Green Blk",
      type: "ACADEMIC",
      footprint: [[-55, -60], [-55, -15], [-5, -15], [-5, -60]],
      height: 16,
      floors: 4,
      color: "#8FAF8F",
      roofColor: "#5A7A5A",
      windowColor: "#73C6A0",
      departments: ["Research", "Space Tech Club", "Seminar Halls"],
      iotSensors: ["energy", "occupancy", "air_quality"],
      landmark: false,
    },
    {
      id: "workshop_block",
      name: "Workshop & Lab Block",
      shortName: "Workshop",
      type: "LAB",
      footprint: [[30, -65], [30, -20], [80, -20], [80, -65]],
      height: 10,
      floors: 2,
      color: "#9B8B7B",
      roofColor: "#6B5B4B",
      windowColor: "#A0B8C8",
      departments: ["Mechanical Workshop", "ECE Lab", "Physics Lab"],
      iotSensors: ["energy", "temperature", "machinery_vibration"],
      landmark: false,
    },
    {
      id: "library",
      name: "Central Library",
      shortName: "Library",
      type: "LIBRARY",
      footprint: [[-25, -100], [-25, -70], [25, -70], [25, -100]],
      height: 14,
      floors: 3,
      color: "#D4C4A0",
      roofColor: "#A09070",
      windowColor: "#C8E0F0",
      departments: ["Library", "OPAC", "E-Resources", "IEEE Digital"],
      iotSensors: ["energy", "occupancy", "temperature"],
      landmark: false,
    },
    {
      id: "admin_block",
      name: "Administration Block",
      shortName: "Admin",
      type: "ADMIN",
      footprint: [[35, -100], [35, -70], [75, -70], [75, -100]],
      height: 20,
      floors: 4,
      color: "#C0B090",
      roofColor: "#907050",
      windowColor: "#6090C0",
      departments: ["Principal Office", "Admissions", "Finance", "HR"],
      iotSensors: ["energy", "occupancy"],
      landmark: true,
    },
    {
      id: "canteen",
      name: "Canteen & Food Court",
      shortName: "Canteen",
      type: "AMENITY",
      footprint: [[-60, 50], [-60, 90], [-10, 90], [-10, 50]],
      height: 7,
      floors: 1,
      color: "#E8A060",
      roofColor: "#C07840",
      windowColor: "#FFD080",
      departments: ["Cafeteria", "Food Court"],
      iotSensors: ["occupancy", "temperature"],
      landmark: false,
    },
    {
      id: "sports_complex",
      name: "Sports Complex",
      shortName: "Sports",
      type: "SPORTS",
      footprint: [[85, 20], [85, 90], [150, 90], [150, 20]],
      height: 9,
      floors: 1,
      color: "#78A860",
      roofColor: "#507840",
      windowColor: "#90D080",
      departments: ["Volleyball", "Badminton", "Cricket", "Gym", "Table Tennis"],
      iotSensors: ["energy", "occupancy"],
      landmark: false,
    },
    {
      id: "rit_hostel",
      name: "RIT Hostel (Boys)",
      shortName: "RIT Hostel",
      type: "HOSTEL",
      footprint: [[-130, -40], [-130, 20], [-100, 20], [-100, -40]],
      height: 24,
      floors: 6,
      color: "#E8D5B0",
      roofColor: "#C0A880",
      windowColor: "#A0C0E0",
      departments: ["Boys Hostel", "Internet", "Washing"],
      iotSensors: ["energy", "occupancy", "water_usage"],
      landmark: false,
    },
    {
      id: "ima_hostel",
      name: "IMA Hostel (Girls)",
      shortName: "IMA Hostel",
      type: "HOSTEL",
      footprint: [[-130, 30], [-130, 90], [-100, 90], [-100, 30]],
      height: 24,
      floors: 6,
      color: "#F0D8C0",
      roofColor: "#C8A890",
      windowColor: "#B0C8E0",
      departments: ["Girls Hostel", "Dining Hall", "Medical"],
      iotSensors: ["energy", "occupancy", "water_usage"],
      landmark: false,
    },
    {
      id: "rmc_hostel",
      name: "RMC Hostel Block",
      shortName: "RMC Hostel",
      type: "HOSTEL",
      footprint: [[-170, -10], [-170, 60], [-140, 60], [-140, -10]],
      height: 28,
      floors: 7,
      color: "#DDD0B8",
      roofColor: "#B0A080",
      windowColor: "#98B8D8",
      departments: ["RMC Medical College Hostel", "Best Infrastructure"],
      iotSensors: ["energy", "occupancy", "water_usage"],
      landmark: false,
    },
    {
      id: "main_gate",
      name: "Main Gate & Security",
      shortName: "Main Gate",
      type: "GATE",
      footprint: [[-8, -145], [-8, -125], [8, -125], [8, -145]],
      height: 8,
      floors: 1,
      color: "#D4A020",
      roofColor: "#A07010",
      windowColor: "#FFD040",
      departments: ["Security", "Visitor Registration", "Transport"],
      iotSensors: ["occupancy"],
      landmark: true,
    },
    {
      id: "placement_cell",
      name: "Training & Placement Cell",
      shortName: "T&P Cell",
      type: "OFFICE",
      footprint: [[82, -100], [82, -70], [120, -70], [120, -100]],
      height: 12,
      floors: 3,
      color: "#A0B8D0",
      roofColor: "#708090",
      windowColor: "#60A0E0",
      departments: ["Placement", "Training", "Industry Connect"],
      iotSensors: ["energy", "occupancy"],
      landmark: false,
    },
  ],
  ROADS: [
    { points: [[0, -145], [0, -120], [0, -80], [0, -30], [0, 20], [0, 80]], width: 8, type: "main" },
    { points: [[-170, 0], [-130, 0], [-55, 0], [0, 0], [30, 0], [85, 0], [150, 0]], width: 6, type: "main" },
    { points: [[-170, 90], [-130, 90], [-60, 90], [-10, 90], [0, 90], [85, 90], [150, 90]], width: 5, type: "perimeter" },
    { points: [[-130, -40], [-130, 90]], width: 4, type: "service" },
    { points: [[85, -100], [85, 20], [85, 90]], width: 4, type: "service" },
  ],
  TREE_CLUSTERS: [
    { cx: -80, cz: -100, count: 12, spread: 25 },
    { cx: 55, cz: 60, count: 8, spread: 20 },
    { cx: -30, cz: 110, count: 10, spread: 18 },
    { cx: 115, cz: 50, count: 15, spread: 30 },
    { cx: 10, cz: -115, count: 6, spread: 12 },
    { cx: -90, cz: 50, count: 7, spread: 15 },
  ],
  SENSOR_LABELS: {
    energy: { icon: "⚡", unit: "%", label: "Energy Usage" },
    occupancy: { icon: "👥", unit: "%", label: "Occupancy" },
    temperature: { icon: "🌡", unit: "°C", label: "Temperature" },
    air_quality: { icon: "💨", unit: "AQI", label: "Air Quality" },
    water_usage: { icon: "💧", unit: "%", label: "Water Usage" },
    machinery_vibration: { icon: "⚙", unit: "Hz", label: "Machinery Vibration" },
  },
};

export default RIT_CAMPUS;
