spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:rit_digital_twin}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true"
    username: ${DB_USER:ritapp}
    password: ${DB_PASSWORD}

  flyway:
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false

logging:
  level:
    com.university.erp: INFO
    org.hibernate.SQL: WARN
    org.flywaydb: WARN
