spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/rit_digital_twin?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true"
    username: root
    password: "123456"

  flyway:
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false

logging:
  level:
    com.university.erp: INFO
    org.hibernate.SQL: WARN
    org.flywaydb: WARN
